
package Telas;
import Controle.Conexao;
import Joption.Joption;
import Joption.Joptionx;
import Reportes.Reporte;
import Utilitarios.BLDatas;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.IOException;
import java.security.Principal;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;

/**
 *
 * @author Valmir Junior
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Connection conexao = null;

    
    Joption icon = new Joption();
    Joptionx save = new Joptionx(); 
    
    
    
    
    public MenuPrincipal() {
        initComponents();
        
        btnCadastroUsuarios.setVisible(false);
        btnRelatorios.setVisible(false);
        btnsobre.setVisible(false);
        btnViaturasLancadas.setVisible(false);
        btnCadastroTrocas.setVisible(false);
        
       
        
        
        
        
        
         configurar();
         setExtendedState(MAXIMIZED_BOTH);
         setIcon(); 
         Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
         LookAndFeel();
         conexao = Conexao.conector(); 
           jLabel1.setSize(screen);

           jPanel1.setLayout(new FlowLayout());
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCadastro = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnSistema = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnRelatorio = new javax.swing.JMenu();
        jMenuUtilitários = new javax.swing.JMenu();
        jMenuBlocodeNotas = new javax.swing.JMenuItem();
        jMenuCalculadora = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlData2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        btnCadastroUsuarios = new javax.swing.JButton();
        btnCadastroTrocas = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnViaturasLancadas = new javax.swing.JButton();
        btnsobre = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        btnCadastro1 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnRelatorio1 = new javax.swing.JMenu();
        btnPesquisar = new javax.swing.JMenu();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        btnSistema1 = new javax.swing.JMenu();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuUtilitários1 = new javax.swing.JMenu();
        jMenuBlocodeNotas1 = new javax.swing.JMenuItem();
        jMenuCalculadora1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmenusair1 = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/medilar2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnCadastro.setBorder(null);
        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/modificar.png"))); // NOI18N
        btnCadastro.setText("Cadastros");
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastroMouseClicked(evt);
            }
        });
        btnCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastroKeyPressed(evt);
            }
        });
        btnCadastro.add(jSeparator1);

        jMenuBar1.add(btnCadastro);

        btnSistema.setBorder(null);
        btnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_os.png"))); // NOI18N
        btnSistema.setText("Sistema");
        btnSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSistemaMouseClicked(evt);
            }
        });
        btnSistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSistemaKeyPressed(evt);
            }
        });
        btnSistema.add(jSeparator2);
        btnSistema.add(jSeparator4);

        jMenuBar1.add(btnSistema);

        btnRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setBorder(null);
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        btnRelatorio.setText("Relatórios       ");
        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnRelatorio);

        jMenuUtilitários.setBorder(null);
        jMenuUtilitários.setText("Utilitários");
        jMenuUtilitários.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuBlocodeNotas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        jMenuBlocodeNotas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBlocodeNotas.setText("Bloco de Notas");
        jMenuBlocodeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBlocodeNotasActionPerformed(evt);
            }
        });
        jMenuUtilitários.add(jMenuBlocodeNotas);

        jMenuCalculadora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCalculadora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuCalculadora.setText("Calculadora");
        jMenuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalculadoraActionPerformed(evt);
            }
        });
        jMenuUtilitários.add(jMenuCalculadora);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setText("Calendário");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuUtilitários.add(jMenuItem5);

        jMenuBar1.add(jMenuUtilitários);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sys - Estacionamento - V-01");
        setBackground(new java.awt.Color(255, 255, 51));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Usuário Logado:");

        jlData2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlData2.setForeground(new java.awt.Color(255, 0, 0));
        jlData2.setText("data");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setText("Usuário");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Data/Hora de login: - ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlData2)
                .addGap(13, 13, 13))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jlData2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jToolBar3.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar3.setBorder(null);
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);
        jToolBar3.setOpaque(false);

        btnCadastroUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastroUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/us.png"))); // NOI18N
        btnCadastroUsuarios.setText("Cadastro de Usuários");
        btnCadastroUsuarios.setToolTipText("Cadastro de Usuários");
        btnCadastroUsuarios.setFocusable(false);
        btnCadastroUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroUsuarios.setOpaque(false);
        btnCadastroUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsuariosActionPerformed(evt);
            }
        });
        jToolBar3.add(btnCadastroUsuarios);

        btnCadastroTrocas.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastroTrocas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastroTrocas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carros.png"))); // NOI18N
        btnCadastroTrocas.setText("Cadastro de Veiculos");
        btnCadastroTrocas.setToolTipText("Cadastro de Veiculos");
        btnCadastroTrocas.setFocusable(false);
        btnCadastroTrocas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroTrocas.setOpaque(false);
        btnCadastroTrocas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroTrocas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroTrocasActionPerformed(evt);
            }
        });
        jToolBar3.add(btnCadastroTrocas);

        btnRelatorios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf_1.png"))); // NOI18N
        btnRelatorios.setText("Tipo de Relatórios");
        btnRelatorios.setToolTipText("Tipo de Relatórios");
        btnRelatorios.setFocusable(false);
        btnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseClicked(evt);
            }
        });
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        jToolBar3.add(btnRelatorios);

        btnViaturasLancadas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViaturasLancadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carros.png"))); // NOI18N
        btnViaturasLancadas.setText("Consulta Veiculos");
        btnViaturasLancadas.setToolTipText("Consulta Veiculos");
        btnViaturasLancadas.setFocusable(false);
        btnViaturasLancadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViaturasLancadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnViaturasLancadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViaturasLancadasMouseClicked(evt);
            }
        });
        btnViaturasLancadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViaturasLancadasActionPerformed(evt);
            }
        });
        jToolBar3.add(btnViaturasLancadas);

        btnsobre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/in.png"))); // NOI18N
        btnsobre.setText("Sobre o Sistema");
        btnsobre.setToolTipText("Sobre o Sistema");
        btnsobre.setFocusable(false);
        btnsobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsobreActionPerformed(evt);
            }
        });
        jToolBar3.add(btnsobre);

        jMenuBar2.setAutoscrolls(true);
        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnCadastro1.setBorder(null);
        btnCadastro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/modificar.png"))); // NOI18N
        btnCadastro1.setText("Cadastros");
        btnCadastro1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastro1MouseClicked(evt);
            }
        });
        btnCadastro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastro1KeyPressed(evt);
            }
        });
        btnCadastro1.add(jSeparator6);

        jMenuBar2.add(btnCadastro1);

        btnRelatorio1.setBackground(new java.awt.Color(255, 255, 255));
        btnRelatorio1.setBorder(null);
        btnRelatorio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        btnRelatorio1.setText("Relatórios");
        btnRelatorio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRelatorio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorio1MouseClicked(evt);
            }
        });
        jMenuBar2.add(btnRelatorio1);

        btnPesquisar.setBorder(null);
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search_16x16.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisarKeyPressed(evt);
            }
        });
        btnPesquisar.add(jSeparator9);
        btnPesquisar.add(jSeparator10);

        jMenuBar2.add(btnPesquisar);

        btnSistema1.setBorder(null);
        btnSistema1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_os.png"))); // NOI18N
        btnSistema1.setText("Sistema");
        btnSistema1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSistema1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSistema1MouseClicked(evt);
            }
        });
        btnSistema1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSistema1KeyPressed(evt);
            }
        });
        btnSistema1.add(jSeparator7);
        btnSistema1.add(jSeparator8);

        jMenuBar2.add(btnSistema1);

        jMenuUtilitários1.setBorder(null);
        jMenuUtilitários1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/actualizar.png"))); // NOI18N
        jMenuUtilitários1.setText("Utilitários");
        jMenuUtilitários1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuUtilitários1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUtilitários1MouseClicked(evt);
            }
        });

        jMenuBlocodeNotas1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_MASK));
        jMenuBlocodeNotas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBlocodeNotas1.setText("Bloco de Notas");
        jMenuBlocodeNotas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBlocodeNotas1ActionPerformed(evt);
            }
        });
        jMenuUtilitários1.add(jMenuBlocodeNotas1);

        jMenuCalculadora1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCalculadora1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuCalculadora1.setText("Calculadora");
        jMenuCalculadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalculadora1ActionPerformed(evt);
            }
        });
        jMenuUtilitários1.add(jMenuCalculadora1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem6.setText("Calendário");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuUtilitários1.add(jMenuItem6);

        jMenuBar2.add(jMenuUtilitários1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salir.png"))); // NOI18N
        jMenu2.setText("Sair");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoff.png"))); // NOI18N
        jMenuItem2.setText("LogOff");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jmenusair1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jmenusair1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmenusair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salir.png"))); // NOI18N
        jmenusair1.setText("Sair");
        jmenusair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenusair1ActionPerformed(evt);
            }
        });
        jMenu2.add(jmenusair1);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 1793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 849, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sair() {
        int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair da aplicação?", "Sair", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
           System.exit(0);
    } 
   }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       sair();
    }//GEN-LAST:event_formWindowClosing

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("carros.png")));
    }
    
    private void btnCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuariosActionPerformed
        CadastroUsuarios cadUsuarios = new CadastroUsuarios();
        cadUsuarios.setLocationRelativeTo(null);
        cadUsuarios.setVisible(true);
    }//GEN-LAST:event_btnCadastroUsuariosActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
 
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnsobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsobreActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Programa: Sys Estacionamento!\nProgramador: Valmir Junior \nEmail:valmirchjr@gmail.com\nTel.: (11) 97200-0777\nSite:www.usf.edu.br", "Sobre", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnsobreActionPerformed

    private void btnCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseClicked


        
        btnCadastroUsuarios.setEnabled(true);
        btnRelatorios.setEnabled(false);
        btnsobre.setEnabled(false);
       
    }//GEN-LAST:event_btnCadastroMouseClicked

    private void btnCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastroKeyPressed

    }//GEN-LAST:event_btnCadastroKeyPressed

    private void btnSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistemaMouseClicked

        
        btnCadastroUsuarios.setEnabled(false);
        btnRelatorios.setEnabled(false);
        btnsobre.setEnabled(true);
        
    }//GEN-LAST:event_btnSistemaMouseClicked

    private void btnSistemaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSistemaKeyPressed

    }//GEN-LAST:event_btnSistemaKeyPressed

    private void btnRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseClicked

        
        btnCadastroUsuarios.setEnabled(false);
        btnRelatorios.setEnabled(true);
        btnsobre.setEnabled(false);
  
    }//GEN-LAST:event_btnRelatorioMouseClicked

    private void jMenuBlocodeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBlocodeNotasActionPerformed


        try {
            Runtime.getRuntime().exec("C:\\Windows\\notepad.exe");
        } catch (java.io.IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuBlocodeNotasActionPerformed

    private void jMenuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalculadoraActionPerformed


        try {
            Runtime.getRuntime().exec("cmd.exe /C start calc.exe");
        } catch (IOException E) {
            System.out.println(E);
        }
    }//GEN-LAST:event_jMenuCalculadoraActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Calendário calendario = new Calendário();
        calendario.setVisible(true);
        calendario.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnCadastro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastro1MouseClicked


     
      btnCadastroUsuarios.setVisible(true);
      btnRelatorios.setVisible(false);
      btnsobre.setVisible(false); 
      btnCadastroTrocas.setVisible(true);
      
      
      
      
      btnRelatorios.setVisible(false);
      btnViaturasLancadas.setVisible(false);
     
      
    }//GEN-LAST:event_btnCadastro1MouseClicked

    private void btnCadastro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastro1KeyPressed

    }//GEN-LAST:event_btnCadastro1KeyPressed

    private void btnSistema1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistema1MouseClicked

        
      
      btnCadastroUsuarios.setVisible(false);
      btnRelatorios.setVisible(false);
      btnsobre.setVisible(true); 
      btnRelatorios.setVisible(false);
      btnViaturasLancadas.setVisible(false);
      btnCadastroTrocas.setVisible(false);
    
      
      
        
    }//GEN-LAST:event_btnSistema1MouseClicked

    private void btnSistema1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSistema1KeyPressed

    }//GEN-LAST:event_btnSistema1KeyPressed

    private void btnRelatorio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorio1MouseClicked

        btnRelatorios.setVisible(true);
        btnCadastroUsuarios.setVisible(false);
        btnsobre.setVisible(false);
        btnCadastroTrocas.setVisible(false);
        
    }//GEN-LAST:event_btnRelatorio1MouseClicked

    private void jMenuBlocodeNotas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBlocodeNotas1ActionPerformed


        try {
            Runtime.getRuntime().exec("C:\\Windows\\notepad.exe");
        } catch (java.io.IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuBlocodeNotas1ActionPerformed

    private void jMenuCalculadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalculadora1ActionPerformed


        try {
            Runtime.getRuntime().exec("cmd.exe /C start calc.exe");
        } catch (IOException E) {
            System.out.println(E);
        }
    }//GEN-LAST:event_jMenuCalculadora1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Calendário calendario = new Calendário();
        calendario.setVisible(true);
        calendario.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        
     
      btnCadastroUsuarios.setVisible(false);
      btnRelatorios.setVisible(false);
      btnViaturasLancadas.setVisible(true);
      btnsobre.setVisible(false);
      btnCadastroTrocas.setVisible(false);
      btnRelatorios.setVisible(false);
      
      
        
//        btnCadastroPacientes.setEnabled(false);
//        btnCadastroUsuarios.setEnabled(false);
//        btnRelatorios.setEnabled(false);
//        btnTelaViaturas.setEnabled(false);
//        btnTelaPesquisa.setEnabled(true);
//        btnsobre.setEnabled(false);
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarKeyPressed

    private void btnRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseClicked
        
//        btnRelatorios.setVisible(false);
//        btnRelatorioPaciente.setVisible(true);
//        btnRelatorioUsuario.setVisible(true);
//        btnRelatorioPacienteStatus.setVisible(true);
//        btnVTRCadastradas.setVisible(true);
//        btnPacientesPorDatas.setVisible(true);
//        btnPacientesPorDatas.setVisible(true);
//        btnExtratos.setVisible(true);
       
        TelaRelatorios tela = new TelaRelatorios();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
      
    }//GEN-LAST:event_btnRelatoriosMouseClicked

    private void btnViaturasLancadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViaturasLancadasMouseClicked

    }//GEN-LAST:event_btnViaturasLancadasMouseClicked

    private void btnViaturasLancadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViaturasLancadasActionPerformed
       
        TelaConsultaVeiculos consultaVtr = new TelaConsultaVeiculos();
        consultaVtr.setLocationRelativeTo(null);
        consultaVtr.setVisible(true);
    }//GEN-LAST:event_btnViaturasLancadasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         int logof = JOptionPane.showConfirmDialog(null, "Deseja efetuar logof do sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (logof == JOptionPane.YES_OPTION) {

 
        MenuPrincipal Menu = new MenuPrincipal();
        Menu.setVisible(true);
         
         Login login = new Login(null, true);
         login.setLocationRelativeTo(login);
         login.setVisible(true);

             try {
                 conexao.close();
             } catch (SQLException ex) {
                 Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    }
    private void jmenusair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenusair1ActionPerformed

        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair ?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
         JOptionPane.showMessageDialog(null,"Sistema Finalizado","ESTACIONAMENTO",JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }

    
     

    }//GEN-LAST:event_jmenusair1ActionPerformed

    private void jMenuUtilitários1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUtilitários1MouseClicked
        btnsobre.setVisible(false);
        btnCadastroTrocas.setVisible(false);
       
    }//GEN-LAST:event_jMenuUtilitários1MouseClicked

    private void btnCadastroTrocasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroTrocasActionPerformed
        TelaVeiculos tela = new TelaVeiculos();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_btnCadastroTrocasActionPerformed
   
    private void configurar() {

        BLDatas bLDatas = new BLDatas();
        jlData2.setText(bLDatas.retornarDataHora());
    }
    
    public void LookAndFeel() {
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        
        
        MenuPrincipal Menu = new MenuPrincipal();
        Menu.setVisible(true);
         
         Login login = new Login(null, true);
         login.setLocationRelativeTo(login);
         login.setVisible(true);
         
         
        
               
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnCadastro;
    private javax.swing.JMenu btnCadastro1;
    private javax.swing.JButton btnCadastroTrocas;
    private javax.swing.JButton btnCadastroUsuarios;
    private javax.swing.JMenu btnPesquisar;
    private javax.swing.JMenu btnRelatorio;
    private javax.swing.JMenu btnRelatorio1;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JMenu btnSistema;
    private javax.swing.JMenu btnSistema1;
    private javax.swing.JButton btnViaturasLancadas;
    private javax.swing.JButton btnsobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuBlocodeNotas;
    private javax.swing.JMenuItem jMenuBlocodeNotas1;
    private javax.swing.JMenuItem jMenuCalculadora;
    private javax.swing.JMenuItem jMenuCalculadora1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuUtilitários;
    private javax.swing.JMenu jMenuUtilitários1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel jlData2;
    private javax.swing.JMenuItem jmenusair1;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

        
}
