
package Telas;

import Controle.Conexao;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Valmir Junior
 */
public class TelaRelatorios extends JFrame implements ActionListener {
    Connection conexao = null;
   

    public TelaRelatorios() {
        initComponents();
        setSize(600,205);

        conexao = Conexao.conector();
     
          btnRelatorioPaciente.setVisible(false);
          btnRelatorioPacienteStatus.setVisible(false);
          btnRelatorioUsuario.setVisible(false);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelatorioUsuario = new javax.swing.JButton();
        btnRelatorioPacienteStatus = new javax.swing.JButton();
        btnRelatorioPaciente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jcRelatorios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Relatórios");

        btnRelatorioUsuario.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btnRelatorioUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        btnRelatorioUsuario.setText("Usuários Cadastrados");
        btnRelatorioUsuario.setToolTipText("Relatório Usuários Cadastrados");
        btnRelatorioUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRelatorioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioUsuarioActionPerformed(evt);
            }
        });

        btnRelatorioPacienteStatus.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btnRelatorioPacienteStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        btnRelatorioPacienteStatus.setText("Veiculos por Placa");
        btnRelatorioPacienteStatus.setToolTipText("Relatório Veiculos por Placas");
        btnRelatorioPacienteStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRelatorioPacienteStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPacienteStatusActionPerformed(evt);
            }
        });

        btnRelatorioPaciente.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btnRelatorioPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        btnRelatorioPaciente.setText("Veiculos Cadastrados");
        btnRelatorioPaciente.setToolTipText("Relatório Veiculos Cadastrados");
        btnRelatorioPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRelatorioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPacienteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jcRelatorios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcRelatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Relatório Veiculos", "Relatório Veiculos por Placa", "Relatório Usuários", " ", " " }));
        jcRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcRelatoriosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Selecione  o Relatório  ----->");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jcRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRelatorioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioPacienteStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatorioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRelatorioPaciente, btnRelatorioPacienteStatus, btnRelatorioUsuario});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRelatorioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRelatorioPacienteStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRelatorioPaciente, btnRelatorioPacienteStatus, btnRelatorioUsuario});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioUsuarioActionPerformed

        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatorio?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {

            final Aguarde carregando = new Aguarde();
            carregando.setVisible(true);
            Thread t = new Thread(){
                public void run(){

                    try {

                        JasperPrint print = JasperFillManager.fillReport("C:/RelatorioVeiculos/usuarios.jasper", null, conexao);

                        JasperViewer.viewReport(print, false);
                        carregando.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            t.start();

        }
    }//GEN-LAST:event_btnRelatorioUsuarioActionPerformed

    private void btnRelatorioPacienteStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPacienteStatusActionPerformed

            final Aguarde carregando = new Aguarde();
            carregando.setVisible(true);
            Thread t = new Thread(){
                public void run(){

                    try {

                        String parametro = JOptionPane.showInputDialog(" Digite a Placa do Veiculo");
                        Map parametros = new HashMap();
                        parametros.put("Placa", parametro);


                        JasperPrint print = JasperFillManager.fillReport("C:/RelatorioVeiculos/VeiculosporPlaca.jasper", parametros, conexao);

                        JasperViewer.viewReport(print, false);
                        carregando.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            t.start();

            //        }
    }//GEN-LAST:event_btnRelatorioPacienteStatusActionPerformed

    private void btnRelatorioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPacienteActionPerformed

        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatorio?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {

            final Aguarde carregando = new Aguarde();
            carregando.setVisible(true);
            Thread t = new Thread(){
                public void run(){

                    try {

                        JasperPrint print = JasperFillManager.fillReport("C:/RelatorioVeiculos/Veiculos.jasper", null, conexao);

                        JasperViewer.viewReport(print, false);
                        carregando.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            t.start();

        }
    }//GEN-LAST:event_btnRelatorioPacienteActionPerformed

    private void jcRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcRelatoriosActionPerformed
//      String s = (String)jcRelatorios.getSelectedItem();
//        JOptionPane.showMessageDialog(this," Você selecionou " + s);
        

          if (jcRelatorios.getSelectedItem().toString().equals("Relatório Veiculos")) {
            
            btnRelatorioPaciente.setVisible(true);
            btnRelatorioPacienteStatus.setVisible(false);
            btnRelatorioUsuario.setVisible(false);
            

        } else if (jcRelatorios.getSelectedItem().toString().equals("Relatório Veiculos por Placa")) {
            
            btnRelatorioPacienteStatus.setVisible(true);
            btnRelatorioPaciente.setVisible(false);
            btnRelatorioUsuario.setVisible(false);
            
            
        } else if (jcRelatorios.getSelectedItem().toString().equals("Relatório Usuários")) {
            
            btnRelatorioUsuario.setVisible(true);
            btnRelatorioPaciente.setVisible(false);
            btnRelatorioPacienteStatus.setVisible(false);
            
            
        }
          
         
    }//GEN-LAST:event_jcRelatoriosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelatorioPaciente;
    private javax.swing.JButton btnRelatorioPacienteStatus;
    private javax.swing.JButton btnRelatorioUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcRelatorios;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
